### ISSUE TITLE
Permission denied when trying to install on Mac

### ISSUE THREAD

**Issue by dconley01** [chbrown/overdrive#11]
Hello! When I try to starting the installation process using the 
```sh
curl https://chbrown.github.io/overdrive/overdrive.sh > /usr/local/bin/overdrive
chmod +x /usr/local/bin/overdrive
```
in my Mac terminal, it tells me that permission is denied. How can I fix this?

**Comment by chbrown** [comment]
Hi! First off, be sure you're running those as two different commands, not on the same line :)

More to the point... I'm not sure which of the two commands is failing with the "permission denied" error, but if it's the `chmod ...`, you may need to call it with sudo, i.e., 
```sh
sudo chmod +x /usr/local/bin/overdrive
```
and enter your password when requested.

### Alternatively...

You don't _have_ to install the script into `/usr/local/bin`, but that's usually on users' `PATH`, so it's convenient. If you have trouble with `sudo` or whatever, you can avoid worrying about permissions and just put the script in your `HOME` folder:

```sh
curl https://chbrown.github.io/overdrive/overdrive.sh > ~/overdrive
chmod +x ~/overdrive
```

Then, instead of running it like most of the examples in the README, e.g., `overdrive --help`, you'll have to run `~/overdrive --help`.
Not quite as pretty, but works exactly the same.

**Comment by dconley01** [comment]
So I was entering it in as one line, but it seems that the "curl https://chbrown.github.io/overdrive/overdrive.sh > /usr/local/bin/overdrive: is the denied one. I tried entering it as "sudo curl https://chbrown.github.io/overdrive/overdrive.sh > /usr/local/bin/overdrive" and still was denied. Any idea?

**Comment by chbrown** [comment]
Ah 😞 that's because `sudo` only affects the immediate command (`curl`), not the shell redirection part, i.e., the `>` and subsequent filepath. 

### To do it all with `sudo`:

Download the script:
```sh
sudo curl https://chbrown.github.io/overdrive/overdrive.sh -o /usr/local/bin/overdrive
```
Then mark it executable:
```sh
sudo chmod +x /usr/local/bin/overdrive
```

### Great, it's installed! But is it ready to use?

Ensure `/usr/local/bin` is on your PATH:
```sh
echo $PATH
```
(`/usr/local/bin` should be in there _somewhere_ as one of the `:`-separated paths)

**If it's not**, you'll need to call this:
```sh
export PATH="/usr/local/bin:$PATH"
```
and you'll need to call that _every time you open a new terminal_ unless you [add it to your shell startup scripts](https://www.google.com/search?q=permanently+set+PATH+.bashrc).

### Be optimistic!

At this point, the examples from the README _should_ (:pray) work.

**Comment by dconley01** [comment]
so I actually had to and use the root shell to install it for some reason, but when I try to download it now, it says the command is not found? I checked the readme but there doesn't seem to be anything in it about that?

**Comment by chbrown** [comment]
Yeah if you see something like 
```console
-bash: overdrive: command not found
```
that means it might be: a) not on your PATH, or b) not executable, or both. See the "**But is it ready to use?**" section from my last comment.

At this point I'm also inclined to (re-)suggest using it like I described in the "**Alternatively...**" section in my first comment on this issue :)

**Comment by dconley01** [comment]
Generating random ClientID=37518480-7ED9-41EC-B712-D73EF22B616E
/usr/local/bin/overdrive: line 70: xmlstarlet: command not found This is what I see when I try to download after trying to execute the path. 

And I tried running it that way, but even though it installed, it is giving me the same line 70 xmstarlet not found.

**Comment by chbrown** [comment]
Oooh, that's progress though! 

Sounds like you don't have [`xmlstarlet`](http://xmlstar.sourceforge.net/) installed. Easiest way is probably to install [Homebrew](https://brew.sh/) and use it to install xmlstarlet: `brew install xmlstarlet`.

Sorry for yet-one-more-thing-to-do but most of the interesting stuff the overdrive script actually performs involves extracting specific fields from XML, so it's not practically avoidable.

Good luck! Homebrew is totally worth it, and going through that install process will alleviate some of the pains you're having with permissions and executables and PATH :)

**Comment by dconley01** [comment]
Progress is good! 

I just installed both of those and while it still denies me the permission, I am able to go about it the alternate way! Thank you so much! This is going to help me continue going to school!

**Comment by chbrown** [comment]
Glad to hear it works, one way or another :) 

AFAIK there's no difference between returning the loan using `overdrive return *.odm` (or using their app) and returning it on the library website, or simply waiting until your loan expires.

FYI: when returning a loan using the CLI script in this repo, you don't give it the `.odm.license` file, but the original `.odm` that you downloaded from your library's website.

**Comment by dconley01** [comment]
ok! Thank you! Is there another way to contact you besides this thread? I had a question about something similar.

**Comment by chbrown** [comment]
You can email me but if it's about this repo and there's a chance some other `overdrive` user might find the answer useful, I will not answer you by email.

**Comment by jcqbrc** [comment]
I downloaded it successfully (after being unable to) using: 

`curl https://chbrown.github.io/overdrive/overdrive.sh > ~/overdrive`

I confirmed it's correctly on my path using: 

`~/overdrive --help`

But I keep getting _-bash command not found_ errors when downloading. 

From what I'm reading, this may be do to me **not making it executable.** But when I try to make it executable by using: 

`sudo chmod +x /usr/local/bin/overdrive`

I get the same _No such file or directory_ error. 

Perhaps I'm not redirecting it properly with` ~/overdrive`?

**Comment by chbrown** [comment]
The **Install** instructions in the README and the **Alternatively...** approach described earlier in this thread are totally distinct. 

If `~/overdrive --help` works (it should print out `Usage: overdrive command ...` followed by the other options and a Commands section), great! Just continue with the rest of the instructions from the README, replacing e.g. `overdrive return Novel.odm` with `~/overdrive return Novel.odm`.

---
The entire functionality (outside of the external commands it calls, like `xmlstarlet`) exists in the single script you downloaded, so it doesn't matter where you install it to. Putting it in the `/usr/local/bin/` directory is just a sort of filesystem organization 'best practice', but by no means necessary. For instance, another common practice (which is probably how I'll rewrite the README) is to put such executable scripts into `~/.local/bin/` (which wouldn't require any `sudo`'ing) and ensure _that's_ on your PATH, which would only have a tangible effect if you're using a multi-user computer, because other users wouldn't be able to use the script (which might be what you want in some cases).

**Comment by jcqbrc** [comment]
Finally got it after (had to install home-brew then xmlstarlet first). Fantastic. Thank you so much for this tool and the wonderful support. Hopefully, this thread will help others (and save you some support time!). Thanks again!

**Comment by chbrown** [comment]
Congrats! Glad you got it working.

Looks like it's already paying dividends — you figured it out after just two (new) Q&A's 😄
