### ISSUE TITLE
Why do I have to mkdir and curl every time to use this

### ISSUE THREAD

**Issue by thejoel12** [chbrown/overdrive#13]
Novice here - but why do I have to reinstall the script each time I use it. Am I doing something incorrectly when I install it?

**Comment by chbrown** [comment]
I have no idea! Can't really help you out without more information about how you're installing it or how you're using it 😬

**Comment by thejoel12** [comment]
<img width="582" alt="Screen Shot 2020-02-12 at 8 53 57 AM" src="https://user-images.githubusercontent.com/36237806/74352119-4b6a6e00-4d75-11ea-96cb-ce0f67d2d9f7.png">

If I have to reinstall each time it only takes a few seconds but still strange to me. As soon as I close terminal I love overdrive commands. Tried installing it to home instead of /usr/local and I tried sudo for chmod.

**Comment by chbrown** [comment]
Ah, that's much better — your screenshot covers everything I need to give you an answer 👍 

When I saw `zsh` I was about to say something like "and you call yourself a novice 😠" but (TIL) [Apple changed the default shell from `/bin/bash` to `/bin/zsh`](https://en.wikipedia.org/wiki/Z_shell) 😢:
> macOS Catalina, released in October 2019, adopted Zsh as the default shell, replacing Bash.

In short, then, **run through the "installation" _one_ more time, and wherever you see `~/.bashrc`, use `~/.zshrc` instead** (i.e., at the end of the `printf` and `source` commands). 

Please let me know if that works, and I'll update the README with instructions about Zsh vs. Bash.

Btw., in case the suggestion above _doesn't_ work, the only reinstall step that you need to run before each use is the `source ~/.bashrc` command (which is something Bash does when starting up; but since you're using Zsh, it ignores `~/.bashrc` and tries to `source ~/.zshrc`, to no avail).

**Comment by thejoel12** [comment]
Yup that was it. Thanks!
