### ISSUE TITLE
Integrate with LazyLibrarian

### ISSUE THREAD

**Issue by lincalinca** [chbrown/overdrive#18]
I'm using LazyLibrarian to replenish my audiobook library which I lost a little while ago, and while it's pretty good at giving a graphical display of a lot of the content, it's woeful at organising the metadata (using GoodReads as its primary source of truth, which helps for book details, but is rubbish for things like chapters etc).

Using OverDrive appears to be a natural means to resolve that, both in terms of grabbing great quality files, as well as well managed files in terms of chapters etc.

LazyLibrarian has the options to blend files together, and uses a range of options (including FFMPEG) to do so, but still relies on the file data from somewhere.

So I think it would be great to get these two working in harmony together.

**Comment by chbrown** [comment]
Interesting... I wasn't aware of LazyLibrarian, but it looks like a useful tool — like a mashup of GoodReads and Calibre with a dash of Plex.

Can you be more specific about integration? LL is welcome to call out to `overdrive` or otherwise incorporate the functionality in this repo — the MIT license is very permissive — and I'd be open to PR's if something in overdrive needs customization, like output directory/file structure. 

But based on my preliminary understanding, LL would be the tool responsible for acquiring the original ODM files, after which it could fork out to (a vendorized) `overdrive` script and then import the resulting audio files or whatever. So it seems like this ticket belongs in their repo, not here?

**Comment by chbrown** [comment]
Thanks for the pointer to LazyLibrarian, but I'm not sure how it bears on this project, so I'm closing this issue as out of scope.
