### ISSUE TITLE
Add Dependency Package Names / Commands To Docs/Readme

### ISSUE THREAD

**Issue by 9mido** [chbrown/overdrive#25]
First of all, thank you for this awesome program. It works so much better than WINE's overdrive app on linux. 

Just one small suggestion (you don't need to do it but it might help some people). For the 'Prerequisites' section, add this to make it easier for people to figure out the actual package names to install. Another idea is to list one liner commands for each major OS (mac, windows, debian, red hat, arch, etc)

- curl
- uuidgen (uuid-runtime)
- xmllint (libxml2-utils)
- iconv (libc6-dev)
- openssl
- base64 (cl-base64)
- tidy

**Comment by chbrown** [comment]
Good idea :) Same general issue as PR #20, which I've been holding off on because it seems like a lot of overhead for a single shell script, but this doesn't incur much more complexity. I just added a table to https://github.com/chbrown/overdrive#prerequisites — lmk (preferably with a PR!) if you have a one-liner for Red Hat / Fedora / CentOS (I don't have a handy VM running that flavor) or even Windows (though in that case wouldn't people just use WSL?)

Btw I used libc-bin instead of libc6-dev (for `iconv`) and coreutils instead of cl-base64 (for `base64`), which seem more standard?
