### ISSUE TITLE
Missing LICENSE

### ISSUE THREAD

**Issue by TechnologyClassroom** [chbrown/overdrive#28]
I see you have no LICENSE file for this project. The default is copyright.

I would suggest releasing the code under the GPL-3.0-or-later or AGPL-3.0-or-later license so that others are encouraged to contribute changes back to your project.

**Comment by chbrown** [comment]
Umm, AFAIK, there's nothing legally magical about a `LICENSE` file (if I'm wrong on that please enlighten me!) and I have [this](https://github.com/chbrown/overdrive#license):
![image](https://user-images.githubusercontent.com/360279/100956679-f86dcd00-34e6-11eb-9b98-3e34107a4ef7.png)

**Comment by TechnologyClassroom** [comment]
I missed that.  The only magical thing about having a LICENSE file is that it shows up clearly when you view a repository in the first view of the screen making it easier and faster to determine the license of a project.

Would you like me to make a PR to add an MIT license file to your project?

**Comment by chbrown** [comment]
Well, I kinda like the minimalism of having just two files in the repo: one for code, and one with instructions for running the code. Can't do much better than two, barring some kind of Literate Programming hackery, which I doubt GitHub would format properly.

I expect GitHub will eventually add a user setting to select the license used for repo metadata. Or implement something to read the README, because stating the license at the bottom of the README is pretty standard, and anyways, _most_ people know to look there if they want to know what license a project is using.

So thanks but no thanks. I'll stick to two files.
