### ISSUE TITLE
Downloaded MP3 files have very low volume

### ISSUE THREAD

**Issue by MattRK** [chbrown/overdrive#32]
I've noticed that all the audio MP3 files downloaded via this script are very low volume. What's odd is that when I listen to the book in Libby or Overdrive's other apps, the volume is perfectly fine. (Libby at 60% volume on my iPhone requires 95% or 100% volume) Is there a way to adjust this in the script? (E.g. changing the encoding options?)

**Comment by chbrown** [comment]
No. I'm sure you could amp up the volume with a pretty simple ffmpeg call, but this script doesn't touch the encoding; it downloads the original files directly — the only thing it changes is the filename: https://github.com/chbrown/overdrive/blob/7157af2/overdrive.sh#L201-L206

It's possible that your library provides .odm files with multiple versions of each file, at different volumes, but I've never seen that. If that were the case, I'd be happy to accept a PR to select some set of versions. Otherwise, closing this as out of scope.
