### ISSUE TITLE
Feature suggestion - automate .odm retrieval

### ISSUE THREAD

**Issue by bedge** [chbrown/overdrive#60]
First of all, thanks for the work, this is a fantastic piece of red tape elimination.
I'm lazy and dislike needing to flip my browser UserAgent.
I started poking at it, but it exceeds my time budget, (while simply complaining that it doesn't already do this, does not), but it looks like one could automate the ,odm file retrieval from the library once one has an authenticated session.
A web scraper with the appropriate useragent should be able to retrieve all eligible/checked-out odm files.

Heck, at that point, you could add a `pull odm's + download book + return + delete old odm's` wrapper/feature. 

Again, thanks for the great work and apologies for submitting this as a feature req instead of a PR.

**Comment by chbrown** [comment]
You're welcome :)

Also annoyed by the User-Agent thing but not enough to do anything about it.

No apology needed; I've turned down a similar PR before: #31

Which is to say, if you want to write a wrapper script, or web scraper, by all means go for it, but I won't be incorporating it into this repo. (Web scraping is especially finicky and tends to need constant maintenance, which is not a great open source experience.)

OTOH if there's some change to this script that makes it friendlier to hook into / more convenient to call from wrapper scripts, I'm all ears. (E.g., I added [3f94f8c](https://github.com/chbrown/overdrive/commit/3f94f8c57c10b58156d2150226767129772652d8) because some books resulted in unpredictable output names and that made it easier for my own wrapper script to find the output.)
